# Setup
# Name of your blog (this will show up at the top of your page and in the RSS feed)
title:            Lucas Callado | Blog
name:             Lucas Callado | Blog
tagline:          'Full Stack Web Development -- Best Practices Coding'
# Short description (goes below the title; it will also be used in the RSS feed)
description:      'Base Jekyll Blog on GitHub'
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url:              http://lucascallado.github.io/

# Your name, as you want it to appear underneath each post and in the footer
author:
  name:           'Lucas Callado'
  url:            http://lucascallado.com

# Dependencies
markdown:         kramdown

# How many articles do you wish to appear on the front page:
paginate:         1

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/lucascallado/lucascallado.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       ['About', 'Archive']

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Your disqus username, entering this will enable commenting on posts
disqus: lucascallado
