# Setup
# Name of your blog (this will show up at the top of your page and in the RSS feed)
title:            LucasCallado.GitHub.io
name:             LucasCallado.GitHub.io
tagline:          'Full Stack Senior Web Developer'
# Short description (goes below the title; it will also be used in the RSS feed)
description:      'Base Jekyll Blog on GitHub'
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url:              http://lucascallado.github.io/

# Your name, as you want it to appear underneath each post and in the footer
author:
  name:           'Lucas Callado'
  url:            http://lucascallado.com

#### Under the Hood Stuff #####
# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
# markdown: rdiscount
markdown: kramdown

# How many articles do you wish to appear on the front page:
paginate:         1

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/lucascallado/lucascallado.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       ['About', 'Archive','Atom']

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Your disqus username, entering this will enable commenting on posts
disqus: lucascallado